### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by SergeyMi37** [rcemper/native-api-command-line-java#1]
I try in Ubuntu and RHEL
docker-compose logs
...
native-api-command-line-java-iris-1  | ~ /opt/irisapp
native-api-command-line-java-iris-1  | /opt/irisapp
native-api-command-line-java-iris-1  | [INFO] Executing command /opt/irisapp/src/pre.sh...
native-api-command-line-java-iris-1  | [ERROR] sh: 1: /opt/irisapp/src/pre.sh: Permission denied
native-api-command-line-java-iris-1  | [ERROR] Command "/opt/irisapp/src/pre.sh" exited with status 32256
native-api-command-line-java-iris-1  | [FATAL] Error executing pre-startup command
native-api-command-line-java-iris-1  | ~ /opt/irisapp
native-api-command-line-java-iris-1  | /opt/irisapp
native-api-command-line-java-iris-1  | [INFO] Executing command /opt/irisapp/src/pre.sh...
native-api-command-line-java-iris-1  | [ERROR] sh: 1: /opt/irisapp/src/pre.sh: Permission denied
native-api-command-line-java-iris-1  | [ERROR] Command "/opt/irisapp/src/pre.sh" exited with status 32256
native-api-command-line-java-iris-1  | [FATAL] Error executing pre-startup command
native-api-command-line-java-iris-1  | ~ /opt/irisapp
native-api-command-line-java-iris-1  | /opt/irisapp
native-api-command-line-java-iris-1  | [INFO] Executing command /opt/irisapp/src/pre.sh...
native-api-command-line-java-iris-1  | [ERROR] sh: 1: /opt/irisapp/src/pre.sh: Permission denied
native-api-command-line-java-iris-1  | [ERROR] Command "/opt/irisapp/src/pre.sh" exited with status 32256
native-api-command-line-java-iris-1  | [FATAL] Error executing pre-startup command

**Comment by r-cemper** [comment]
**very strange**
I run this in DockerDesktop for Windows without problems:

D:\GitHub\native-api-command-line-java>docker-compose up -d   && docker-compose logs -f
[+] Building 0.0s (0/0)                                                                               docker:default
[+] Running 2/2
 ✔ Network native-api-command-line-java_default   Created                                                       0.1s
 ✔ Container native-api-command-line-java-iris-1  Started                                                       0.2s
native-api-command-line-java-iris-1  | ~ /opt/irisapp
native-api-command-line-java-iris-1  | /opt/irisapp
native-api-command-line-java-iris-1  | [INFO] Executing command /opt/irisapp/src/pre.sh...
native-api-command-line-java-iris-1  | [INFO] Building...
native-api-command-line-java-iris-1  | [INFO] ...executed command /opt/irisapp/src/pre.sh
native-api-command-line-java-iris-1  | [INFO] Starting InterSystems IRIS instance IRIS...
native-api-command-line-java-iris-1  | [INFO] Starting Control Process
native-api-command-line-java-iris-1  | Global buffer setting requires attention.  Auto-selected 25% of total memory.

**and once up:**
D:\GitHub\native-api-command-line-java>docker-compose exec iris bash
irisowner@8afbb53dc0df:/opt/irisapp$ ls -l
total 20
-rwxr-xr-x 1 root      root       196 Nov 15 20:13 iris.script
-rwxr-xr-x 1 root      root       468 Nov 15 20:13 module.xml
-rw-r--r-- 1 irisowner irisowner 4647 Nov 15 20:16 rcc.class
drwxr-xr-x 4 root      root      4096 Nov 15 20:13 src
irisowner@8afbb53dc0df:/opt/irisapp$ ls -l src/
total 24
drwxr-xr-x 2 root root 4096 Nov 15 20:13 dc
drwxr-xr-x 2 root root 4096 Nov 15 20:13 gbl
-rwxr-xr-x 1 root root  148 Nov 15 20:13 pre.sh
-rwxr-xr-x 1 root root 4610 Nov 15 20:13 rcc.java
-rwxr-xr-x 1 root root  170 Nov 15 20:13 run.sh
irisowner@8afbb53dc0df:/opt/irisapp$ whoami
**irisowner**
irisowner@8afbb53dc0df:/opt/irisapp$ cat src/pre.sh
#!/bin/bash

echo "Building..."
cd /opt/irisapp
javac -classpath /usr/irissys/dev/java/lib/1.8/intersystems-jdbc-3.7.1.jar -d . src/rcc.java
exit 0
irisowner@8afbb53dc0df:/opt/irisapp$ /opt/irisapp/src/pre.sh
Building...
irisowner@8afbb53dc0df:/opt/irisapp$

I retry build with --no-cache

**Comment by r-cemper** [comment]
I have applied 2 changes that have no impact in my docker environment
pls. retry. 
for me, I see no different behaviour

NOW:
D:\GitHub\native-api-command-line-java>docker-compose exec iris bash
irisowner@e65f5a5884b6:/opt/irisapp$ ls -l src/
total 28
drwxr-xr-x 2 irisowner irisowner 4096 Nov 15 20:13 dc
drwxr-xr-x 1 irisowner irisowner 4096 Nov 15 20:13 gbl
-rwxr-xr-x 1 irisowner irisowner  148 Nov 15 20:13 pre.sh
-rwxr-xr-x 1 irisowner irisowner 4610 Nov 15 20:13 rcc.java
-rwxr-xr-x 1 irisowner irisowner  170 Nov 15 20:13 run.sh
irisowner@e65f5a5884b6:/opt/irisapp$

has no effects fo me;  eventually in other environments

**Comment by SergeyMi37** [comment]
This didn't work for Linux.

**Comment by r-cemper** [comment]
you break my trust in docker. 
I just have no access to Linux.  Might be worth a pull request
All it does is a Javac ..... for the example code.

**Comment by SergeyMi37** [comment]
Can you merge and check your PR #1 ?
I can't check in Windows.
