### ISSUE TITLE
Code execution error. Where does the %ZX program come from?

### ISSUE THREAD

**Issue by SergeyMi37** [rcemper/native-api-command-line-java#3]
```
# docker-compose exec iris java rcc

        Welcome to IRIS NativeAPI CommandLine Extension

>>> serverIP [127.0.0.1]:
>>> serverPORT [1972]:
>>> namespace [USER]:
>>> username [_SYSTEM]:
>>> password [SYS]:
Exception -- java.sql.SQLException: Exception thrown on server (code = 1162) : <NOROUTINE>XDCall+9^%SYS.DBSRV *%ZX
```

**Comment by r-cemper** [comment]
I'm surprised again: 
You are missing **zpm "install nacl-server"**
   
This is  iris.script
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")
    zn "USER"
    zpm "install webterminal"
    **zpm "install nacl-server"**
    zpm "load /opt/irisapp/ -v":1
    halt

Should look like this

[USER|nacl-server]      Reload START (C:\InterSystems\IRIS\mgr\.modules\USER\nacl-server\0.0.2\)
[USER|nacl-server]      Reload SUCCESS
[nacl-server]   Module object refreshed.
[USER|nacl-server]      Validate START
[USER|nacl-server]      Validate SUCCESS
[USER|nacl-server]      Compile START
[USER|nacl-server]      Compile SUCCESS
[USER|nacl-server]      Activate START
[USER|nacl-server]      Configure START
[USER|nacl-server]      Configure SUCCESS
[USER|nacl-server]      Activate SUCCESS
USER>

**Comment by SergeyMi37** [comment]
I understood what was going on.
Thank you.
